#version de sintaxis
version: "3.9"

#definir servicios
services:
  proyectos-backend-micro-jenkins:
    container_name: proyectos-backend-micro-jenkins
    image: proyectos-backend-micro-jenkins:v1
    build:
      context: .
    ports:
      - "4001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=4001
    networks:
      - proyectos-app

  balanceador-carga-jenkins:
    container_name: balanceador-carga-jenkins
    image: balanceador-carga-jenkins:v1
    build:
      context: ./balanceador
    ports:
      - "4004:80"
    networks:
      - proyectos-app

networks:
  proyectos-app: